### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by romainfrancois** [jupyter-xeus/xeus-r#27]
Currently the kernel does not work on windows, because e.g. the "Rinterface.h" file is not available on windows. 

We use this file for e.g. `ptr_R_WriteConsoleEx`. The callbacks are implemented differently on this platform. We can get inspiration from `gnuwin32/system.c` in R or similar embedding code in e.g. RStudio. 

In the meantime, I'll disable ci on windows.

**Comment by romainfrancois** [comment]
#3 was a first attempt, but needs to go further

**Comment by SylvainCorlay** [comment]
Closing as #90 was merged.
